function ff = ifdct2(Cl, Gkw)
%%% IFDCT2 implements Two-dimensional Inverse Fast Discrete Circlelet
%%% Transform (IFDCT). ifdct2(Cl, Gkw) returns 2-D inverse Circlelet transform.
%     Inputs:
%         Cl: r-by-k cell data contains CT coefficients. r refers to the
%             number of radii and k refers to the number of filters.
%         Gkw: r-by-k cell data contains  filters for computing CT
%         coefficients. generated by fdct2 function.
%     Output:
%         I: Inverse Fast Discrete Circlelet image.
%
%  written by Omid Sarrafzadeh,
%  Isfahan University of Medical Sciences, Isfahan, Iran
%  Email: o.sarrafzade@gmail.com
%
% If you use the code provided here, please cite the following paper:
% O. Sarrafzadeh, A. Mehri, H. Rabbani, N. Ghane, A. Talebi, "Circlet based
% framework for red blood cells segmentation and counting", in Proc. IEEE
% Workshop on Signal Processing Systems,
% Hangzhou, China, Oct. 14-16, 2015.
%
%  Reference for CT:
%  H. Chauris, I. Karoui, P. Garreau, H. Wackernagel, P. Craneguy, and L.
%  Bertino, "The circlet transform: A robust tool for detecting features
%  with circular shapes," Computers & Geosciences, vol. 37, pp. 331-342,
%  2011.

[row, col] = size(Cl{1,1});
CG = zeros(row,col);
for x=1:size(Cl,1)
    for y=1:size(Cl,2)
        Clw = fft2(Cl{x,y});
        CG = CG+Clw.*conj(Gkw{x,y});
    end
end
ff = ifft2(CG);




        